[package]
name = "xml-files"
version = "0.0.0"
authors = ["Matthew James Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.48"
serde_plain = "0.3.0"
snafu = "0.6.2"
